thinktandem/tandem

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/guides/README.md, docs/guides/contributing-code.md, docs/guides/improve-tandem.md
In order to do that I need to [request a review](https://help.github.com/en/articles/requesting-a-pull-request-review). However, before I do that I want to do some self-checks because I respect my reviewers time and want us to maximize throughput at the highest quality.
THE PERSON WHO SUBMITS THE PR SHOULD PUT THEIR ACCEPTANCE TEST HERE.
The acceptance test should detail the steps the reviewer can take to
1. Replicate the "issue" on the mainline site
2. Showcase the "fix" on the PR environment spun up on platform.sh.
Here is a _very simple_ example you can follow
1. Provide a link …
=> Improve guide

docs/guides/improve-tandem.md
=> fix typo: extand --> extend

.github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/task.md, docs/guides/improve-tandem.md
=> Pirog edits

docs/.vuepress/config.js, docs/manifesto/README.md
=> #30: First pass on mission stuff

.markdownlintrc, docs/manifesto/org.md, docs/manifesto/roles.md
=> #33: List out current and near-future roles and depth chart

docs/.vuepress/config.js, docs/manifesto/sins.md
=> #34: First pass on Tandem SINZ

docs/manifesto/roadmap.md
=> #31: First pass on 2019 goals and roadmap

docs/handbook/benefits.md, docs/handbook/onboarding.md, docs/handbook/paid.md, docs/handbook/tracking.md
=> Move handbook over

docs/.vuepress/config.js, docs/guides/roles-responsibilities.md
=> Issue #89: Port roles/responsibilities doc

docs/guides/invoicing.md
=> #77 Tweak invoicing doc

docs/.vuepress/config.js
=> #47: Add google analytics tracking

docs/.vuepress/config.js
=> #47: Update to distinct GA tracking code for docs site

docs/handbook/onboarding.md
=> #103: Add lando-tandem plugin onboarding docs.

docs/.vuepress/config.js, docs/guides/spinning-up-new-projects.md
=> #78 First pass of the project spin up guide

docs/.vuepress/config.js, docs/guides/README.md, docs/guides/daily-standups.md, docs/guides/eow-meeting.md
=> First pass on official tandem meetings

docs/.vuepress/config.js, docs/guides/handling-emergency-requests.md
=> [WIP] Issue #161: First draft of guide on emergencies.

docs/.vuepress/config.js, package.json, site/.vuepress/config.js, site/blog/test-blog-post.md, site/package.json, site/test/README.md, yarn.lock
=> [WIP] 130/tagz

site/blog/test-blog-post2.md, yarn.lock
=> #130 Update our feeds plugin

site/.platform.app.yaml
=> Adjust p.sh to allow for new feeds

yarn.lock
=> adjust vuepress-plugin-frontmatters-feed

site/.vuepress/config.js, site/.vuepress/theme/components/BaseListLayout.vue, site/.vuepress/theme/layouts/About.vue, site/.vuepress/theme/layouts/Blog.vue, site/.vuepress/theme/layouts/Page.vue, site/.vuepress/theme/layouts/Work.vue, site/pages/drupal.md
=> 178 design pass2

site/.vuepress/config.js, site/.vuepress/theme/components/BaseListLayout.vue, site/.vuepress/theme/layouts/Tag.vue
=> Add in tag page

site/.vuepress/config.js, site/.vuepress/theme/layouts/About.vue, site/.vuepress/theme/layouts/Blog.vue, site/.vuepress/theme/layouts/CaseStudy.vue, site/.vuepress/theme/layouts/Contact.vue, site/.vuepress/theme/layouts/Home.vue, site/.vuepress/theme/layouts/Post.vue, site/.vuepress/theme/layouts/Work.vue
=> Update robots and json ld for pagez

yarn.lock
=> Fix tag sorting

site/work/brandywine-d7-support.md, site/work/chenmed-d8-redesign.md, site/work/clmp-wp-redesign.md, site/work/gohealth-d7-redesign.md, site/work/hosp-d6-support.md, site/work/imsglobal-d8-migration.md, site/work/interact-wp-support.md, site/work/outsell-auth0.md, site/work/outsell-osdata.md, site/work/outsell-tethys.md, site/work/poets-blackbaud.md, site/work/poets-redesign.md
Minor update to some of the case studies.
=> Case study tweaks

.platform/applications.yaml, docs/.vuepress/config.js, site/.vuepress/theme/components/Header.vue
=> More tweaks

site/.vuepress/config.js, site/.vuepress/theme/components/HeroFlex.vue, site/.vuepress/theme/components/TagGrid.vue
=> Viewport and other responive quick fixes

package.json, yarn.lock
=> Fork sitemap plugin to exclude pagination

site/.vuepress/theme/layouts/CaseStudy.vue, site/.vuepress/theme/layouts/Home.vue, yarn.lock
=> Moar fixez

site/blog/2020-06-02-lando-drupal-contributions.md
=> Fix typo comoposer --> composer.

site/blog/2020-10-5-drupal-8-9-migration-performance-tips-and-tricks.md
=> Migration tips article

README.md, plugins/tandem-blog-generate/index.js, plugins/tandem-blog-generate/tasks/tandem-blog-generate.js, plugins/tandem-blog-generate/tasks/tandem-show-containers.js, plugins/tandem-blog-generate/templates/post.template
=> Adding tandem-blog:generate command.

site/.vuepress/theme/layouts/About.vue, site/.vuepress/theme/layouts/Blog.vue, site/.vuepress/theme/layouts/Contact.vue, site/.vuepress/theme/layouts/Home.vue, site/.vuepress/theme/layouts/Work.vue
Minor edits primarily to the page intro text to try and keep stylization but make it appear non-accidental/ESL.
=> Readibility edits for page intro text.

site/.vuepress/theme/components/LocationGrid.vue, site/.vuepress/theme/components/SectionHeader.vue, site/.vuepress/theme/components/WorkSummary.vue, site/.vuepress/theme/layouts/About.vue, site/.vuepress/theme/layouts/Careers.vue, site/.vuepress/theme/layouts/CaseStudy.vue, site/.vuepress/theme/layouts/Post.vue, site/.vuepress/theme/styles/index.styl, site/.vuepress/theme/styles/palette.styl
@reynoldsalec  - this shoudl take care of the typography fixes and bits of chrome/firefox flex issues you were seeing on custom blocks.
=> Thiagospiff

site/.vuepress/theme/layouts/Careers.vue
=> Missing a . And also a clear commit message. 🎉
